import type { Fortune } from './types'

export const FORTUNES: Fortune[] = [
  
  { text: 'Love comes to you.', category: 'love' },
  { text: 'New love appears.', category: 'love' },
  { text: 'Hearts meet soon.', category: 'love' },
  { text: 'Love finds you.', category: 'love' },
  { text: 'Someone thinks of you.', category: 'love' },
  { text: 'Love grows slowly.', category: 'love' },
  { text: 'Open your heart.', category: 'love' },
  { text: 'Trust your heart.', category: 'love' },
  { text: 'Love needs time.', category: 'love' },
  { text: 'Speak with love.', category: 'love' },
  { text: 'Follow your heart.', category: 'love' },
  { text: 'Be kind today.', category: 'love' },
  { text: 'Stars help love.', category: 'love' },
  { text: 'A heart comes close.', category: 'love' },
  { text: 'Love walks with you.', category: 'love' },
  { text: 'Love touches your heart.', category: 'love' },
  { text: 'Warm feelings return.', category: 'love' },
  { text: 'Love answers kindness.', category: 'love' },
  { text: 'A smile opens hearts.', category: 'love' },
  { text: 'Love speaks softly.', category: 'love' },
  
  { text: 'Money comes slowly.', category: 'money' },
  { text: 'Money finds patience.', category: 'money' },
  { text: 'Money grows slowly.', category: 'money' },
  { text: 'A reward comes soon.', category: 'money' },
  { text: 'Your work pays.', category: 'money' },
  { text: 'Money follows effort.', category: 'money' },
  { text: 'Spend wisely today.', category: 'money' },
  { text: 'Save a little today.', category: 'money' },
  { text: 'Think before spending.', category: 'money' },
  { text: 'Value small wins.', category: 'money' },
  { text: 'Be patient with money.', category: 'money' },
  { text: 'Plan your next step.', category: 'money' },
  { text: 'Luck helps money.', category: 'money' },
  { text: 'A coin brings luck.', category: 'money' },
  { text: 'Money changes soon.', category: 'money' },
  { text: 'Luck watches quietly.', category: 'money' },
  { text: 'A chance appears.', category: 'money' },
  { text: 'Luck helps your wallet.', category: 'money' },
  { text: 'More money comes.', category: 'money' },
  { text: 'Stars bless money.', category: 'money' },
  
  { text: 'Energy returns soon.', category: 'health' },
  { text: 'Strength grows inside.', category: 'health' },
  { text: 'Balance returns today.', category: 'health' },
  { text: 'Your body heals.', category: 'health' },
  { text: 'Peace enters your body.', category: 'health' },
  { text: 'Fresh energy appears.', category: 'health' },
  { text: 'Listen to your body.', category: 'health' },
  { text: 'Take time to rest.', category: 'health' },
  { text: 'Drink more water.', category: 'health' },
  { text: 'Slow down today.', category: 'health' },
  { text: 'Care for yourself.', category: 'health' },
  { text: 'Breathe slowly today.', category: 'health' },
  { text: 'Your body knows.', category: 'health' },
  { text: 'Healing begins quietly.', category: 'health' },
  { text: 'The moon brings calm.', category: 'health' },
  { text: 'Nature gives strength.', category: 'health' },
  { text: 'Peace flows inside.', category: 'health' },
  { text: 'Stars send calm.', category: 'health' },
  { text: 'Your spirit feels lighter.', category: 'health' },
  { text: 'Quiet brings healing.', category: 'health' },
  
  { text: 'A new path opens.', category: 'work' },
  { text: 'Success comes slowly.', category: 'work' },
  { text: 'Your effort shines.', category: 'work' },
  { text: 'A chance comes soon.', category: 'work' },
  { text: 'Your talent grows.', category: 'work' },
  { text: 'A door opens.', category: 'work' },
  { text: 'Trust your skills.', category: 'work' },
  { text: 'Focus on progress.', category: 'work' },
  { text: 'Stay patient today.', category: 'work' },
  { text: 'Work with courage.', category: 'work' },
  { text: 'Learn something new.', category: 'work' },
  { text: 'Keep moving forward.', category: 'work' },
  { text: 'Your work finds direction.', category: 'work' },
  { text: 'The path appears.', category: 'work' },
  { text: 'Signs point forward.', category: 'work' },
  { text: 'Your moment comes.', category: 'work' },
  { text: 'Action brings success.', category: 'work' },
  { text: 'Things begin changing.', category: 'work' },
  { text: 'Stars light your path.', category: 'work' },
  { text: 'Success grows slowly.', category: 'work' },
  
  { text: 'A secret becomes clear.', category: 'mystery' },
  { text: 'The answer appears.', category: 'mystery' },
  { text: 'A hidden door opens.', category: 'mystery' },
  { text: 'A sign appears.', category: 'mystery' },
  { text: 'Truth comes slowly.', category: 'mystery' },
  { text: 'A mystery opens.', category: 'mystery' },
  { text: 'Follow the signs.', category: 'mystery' },
  { text: 'Trust your feeling.', category: 'mystery' },
  { text: 'Look deeper today.', category: 'mystery' },
  { text: 'Listen to silence.', category: 'mystery' },
  { text: 'Watch the details.', category: 'mystery' },
  { text: 'Stay curious today.', category: 'mystery' },
  { text: 'Stars whisper softly.', category: 'mystery' },
  { text: 'Life shows clues.', category: 'mystery' },
  { text: 'The universe speaks softly.', category: 'mystery' },
  { text: 'Wind brings answers.', category: 'mystery' },
  { text: 'A quiet truth rises.', category: 'mystery' },
  { text: 'Night holds answers.', category: 'mystery' },
  { text: 'Signs guide you.', category: 'mystery' },
  { text: 'The unknown smiles.', category: 'mystery' },
  
  { text: 'Family joy grows.', category: 'family' },
  { text: 'Warmth fills home.', category: 'family' },
  { text: 'A happy visit comes.', category: 'family' },
  { text: 'Laughter fills home.', category: 'family' },
  { text: 'Family bonds grow.', category: 'family' },
  { text: 'Love returns home.', category: 'family' },
  { text: 'Call your family.', category: 'family' },
  { text: 'Share a meal.', category: 'family' },
  { text: 'Listen with patience.', category: 'family' },
  { text: 'Visit home soon.', category: 'family' },
  { text: 'Offer a hug.', category: 'family' },
  { text: 'Show your care.', category: 'family' },
  { text: 'Home welcomes joy.', category: 'family' },
  { text: 'Family watches kindly.', category: 'family' },
  { text: 'The house feels warm.', category: 'family' },
  { text: 'Family roots grow.', category: 'family' },
  { text: 'A blessing enters home.', category: 'family' },
  { text: 'Kindness returns home.', category: 'family' },
  { text: 'Harmony finds family.', category: 'family' },
  { text: 'The fire feels warm.', category: 'family' },
  
  { text: 'A road appears.', category: 'travel' },
  { text: 'New places wait.', category: 'travel' },
  { text: 'A journey begins.', category: 'travel' },
  { text: 'Adventure comes soon.', category: 'travel' },
  { text: 'Your path grows wider.', category: 'travel' },
  { text: 'The road welcomes you.', category: 'travel' },
  { text: 'Prepare your bags.', category: 'travel' },
  { text: 'Follow the road.', category: 'travel' },
  { text: 'Explore something new.', category: 'travel' },
  { text: 'Leave comfort briefly.', category: 'travel' },
  { text: 'Watch the horizon.', category: 'travel' },
  { text: 'Travel with curiosity.', category: 'travel' },
  { text: 'The wind calls.', category: 'travel' },
  { text: 'Paths cross soon.', category: 'travel' },
  { text: 'The world opens.', category: 'travel' },
  { text: 'Far places call.', category: 'travel' },
  { text: 'The map changes.', category: 'travel' },
  { text: 'A road remembers.', category: 'travel' },
  { text: 'Life sends journeys.', category: 'travel' },
  { text: 'New skies appear.', category: 'travel' },
  
  { text: 'A loyal friend waits.', category: 'pets' },
  { text: 'A happy tail greets.', category: 'pets' },
  { text: 'Soft paws arrive.', category: 'pets' },
  { text: 'Joy follows paws.', category: 'pets' },
  { text: 'A gentle friend appears.', category: 'pets' },
  { text: 'A warm purr comforts.', category: 'pets' },
  { text: 'Play with your pet.', category: 'pets' },
  { text: 'Offer a treat.', category: 'pets' },
  { text: 'Walk together today.', category: 'pets' },
  { text: 'Show gentle care.', category: 'pets' },
  { text: 'Share quiet time.', category: 'pets' },
  { text: 'Listen to paws.', category: 'pets' },
  { text: 'Animals feel truth.', category: 'pets' },
  { text: 'Paws bring luck.', category: 'pets' },
  { text: 'A tail shows joy.', category: 'pets' },
  { text: 'Animals bring calm.', category: 'pets' },
  { text: 'Kind eyes watch.', category: 'pets' },
  { text: 'Loyal hearts protect.', category: 'pets' },
  { text: 'The paw guides.', category: 'pets' },
  { text: 'Fur brings comfort.', category: 'pets' },
  
  { text: 'Luck walks with you.', category: 'luck' },
  { text: 'Good luck smiles.', category: 'luck' },
  { text: 'A bright chance appears.', category: 'luck' },
  { text: 'Luck comes soon.', category: 'luck' },
  { text: 'Your moment comes.', category: 'luck' },
  { text: 'Good luck rises.', category: 'luck' },
  { text: 'Trust your timing.', category: 'luck' },
  { text: 'Be patient today.', category: 'luck' },
  { text: 'Take the chance.', category: 'luck' },
  { text: 'Watch for opportunity.', category: 'luck' },
  { text: 'Stay open today.', category: 'luck' },
  { text: 'Believe in luck.', category: 'luck' },
  { text: 'Stars align quietly.', category: 'luck' },
  { text: 'Luck moves slowly.', category: 'luck' },
  { text: 'The universe helps you.', category: 'luck' },
  { text: 'Luck comes softly.', category: 'luck' },
  { text: 'The wind changes.', category: 'luck' },
  { text: 'A golden path appears.', category: 'luck' },
  { text: 'Luck sends signs.', category: 'luck' },
  { text: 'The stars smile.', category: 'luck' }
    
  // TODO: add more until we have 100 phrases
]

